### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by fhasni** [rqx110/aspnet-zero-rad-tool-vscode#3]
After running the command `Run ASP.NET Zero Rad Tool`
I am getting the following error.

```
-> code generation is begining...
/bin/sh: dotnet.exe: command not found
```

**Comment by rqx110** [comment]
please update your extension from vscode marketplace

**Comment by asimp51** [comment]
You have to select startUp project to Entityframework then run RAD toll
