### ISSUE TITLE
issue with aspnet zero 8.9

### ISSUE THREAD

**Issue by mahmoodiasghar** [rqx110/aspnet-zero-rad-tool-vscode#4]
Hello,
When i try with this on aspnet zero v8.9 it remaining on "code generation is begining.." step without generation any thing. which version of asnet zero you suggest for this extension ?

**Comment by rqx110** [comment]
do you enter your license code in config.json?

**Comment by mahmoodiasghar** [comment]
i have this line as license code "  "LicenseCode": "LicenseCodePlaceHolderToReplace". 
Do i must add more thing  ?

**Comment by rqx110** [comment]
you have to purchase **Aspnet Zero** from the official site www.aspnetzero.com, and put your license code in config.json, and also change the **ProjectType** to a valid value
