### ISSUE TITLE
Master Details CRUD

### ISSUE THREAD

**Issue by weedkiller** [rqx110/aspnet-zero-rad-tool-vscode#5]
Hello, this is an awesome tool 👍  

I am trying to do something like Customers-> Orders details page, can you please help with a Master Details, how do I set that up in the tool please

**Comment by rqx110** [comment]
add a propery(IsMasterDetailPage) in YourEntity.json 
![image](https://user-images.githubusercontent.com/1829209/106402964-2def5200-6467-11eb-93ca-cd3142a6dd00.png)

ps. I forgot add this property to the snippet, I will add it later and I will also update the core of aspnetzeroRadTool to latest version

**Comment by weedkiller** [comment]
Awesome you rock!! 👍
